# Outlined data flow across steps
from pydantic import BaseModel
from typing import Optional

# planner.py
class SearchQuery(BaseModel):
    """A single sub-query generated by the planner."""
    query: str
    purpose: str  # why this sub-query helps cover the topic


class InferredSchema(BaseModel):
    # Data schema inferred by planner
    columns: list[str]
    entity_type: str # e.g. "startup", "restaurant", "tool"
    description: str


class PlannerOutput(BaseModel):
    """Output of the query planner stage."""
    original_query: str
    sub_queries: list[SearchQuery]
    schema: InferredSchema


# search_scrape.py
class SearchResult(BaseModel):
    # Search result from DuckDuckGo.
    url: str
    title: str
    snippet: str
    source_query: str # which sub-query produced this


class ScrapedPage(BaseModel):
    url: str
    title: str
    content: str # cleaned text, truncated to MAX_CONTENT_CHARS
    success: bool
    error: Optional[str] = None


# extractor.py
class CellSource(BaseModel):
    # Tracibility 
    url: str
    snippet: str # the exact text passage supporting this value


class ExtractedEntity(BaseModel):
    attributes: dict[str, Optional[str]] # column_name==value
    sources: dict[str, CellSource] # column_name==provenance
    source_url: str
    confidence: Optional[float] = None


# merger.py
class MergedEntity(BaseModel):
    attributes: dict[str, Optional[str]]
    sources: dict[str, list[CellSource]]
    source_urls: list[str]


# reflection.py
class ReflectionResult(BaseModel):
    # Output of the reflection/gap-analysis stage
    gaps: list[str]
    additional_queries: list[str]
    should_research_more: bool


# final output
class PipelineResult(BaseModel):
    # Final output sent to frontend
    query: str
    schema: InferredSchema
    entities: list[MergedEntity]
    total_sources_consulted: int
    total_pages_scraped: int
    pipeline_stages: list[str] # for progress display
    reflection_rounds: int